import type { DimensionSummary } from "@/lib/ai";

type Props = {
  summary: DimensionSummary;
};

export function DimensionSummaryCard({ summary }: Props) {
  return (
    <div className="mb-6 rounded-lg border border-blue-100 bg-blue-50/50 p-5 dark:border-blue-900/40 dark:bg-blue-950/20">
      <div className="mb-3 flex items-center gap-2">
        <span className="text-xs font-semibold uppercase tracking-wider text-blue-600 dark:text-blue-400">
          AI summary
        </span>
        <span className="text-xs text-zinc-400 dark:text-zinc-500">
          · based on {summary.postCount} practitioner insights
        </span>
      </div>

      <div className="space-y-4">
        <div>
          <p className="mb-1 text-xs font-medium text-zinc-500 dark:text-zinc-400">
            For practitioners
          </p>
          <p className="text-sm leading-relaxed text-zinc-800 dark:text-zinc-200">
            {summary.practitioners}
          </p>
        </div>

        <div>
          <p className="mb-1 text-xs font-medium text-zinc-500 dark:text-zinc-400">
            For leaders
          </p>
          <p className="text-sm leading-relaxed text-zinc-800 dark:text-zinc-200">
            {summary.leaders}
          </p>
        </div>

        <div className="rounded-md border border-orange-200 bg-orange-50 px-3 py-2.5 dark:border-orange-900/40 dark:bg-orange-950/30">
          <p className="mb-1 text-xs font-medium text-orange-600 dark:text-orange-400">
            Watch out for
          </p>
          <p className="text-sm leading-relaxed text-zinc-800 dark:text-zinc-200">
            {summary.watchOut}
          </p>
        </div>
      </div>

      <p className="mt-3 text-xs text-zinc-400 dark:text-zinc-500">
        Generated by Claude · Sourced from high-confidence posts only
      </p>
    </div>
  );
}
